DEFAULT: highcharts

highcharts:
	wget http://www.highcharts.com/downloads/zips/Highcharts-2.2.1.zip
	mkdir static/thirdparty/Highcharts
	mv Highcharts-2.2.1.zip static/thirdparty/Highcharts
	cd static/thirdparty/Highcharts; unzip Highcharts-2.2.1.zip
